# Análisis preliminar del efecto de T en la red LSTM
Requiere `resultados_LSTM_efectoT_random.csv` y `resultados_LSTM_efectoT_TPE.csv` en el mismo directorio.

In [1]:
import pandas as pd

## Visualización de resultados

In [2]:
# BÚSQUEDA ALEATORIA
print(f"{' BÚSQUEDA ALEATORIA ':=^50}")

# CSV principal
df_principal_random = pd.read_csv('resultados_LSTM_efectoT_random.csv')
display(df_principal_random)

# CSV por folds
df_folds_random = pd.read_csv('resultados_LSTM_folds_efectoT_random.csv')
display(df_folds_random)


# ALGORITMO TPE
print(f"\n{' ALGORITMO TPE ':=^50}")

# CSV principal
df_principal_TPE = pd.read_csv('resultados_LSTM_efectoT_TPE.csv')
display(df_principal_TPE)

# CSV por folds
df_folds_TPE = pd.read_csv('resultados_LSTM_folds_efectoT_TPE.csv')
display(df_folds_TPE)

=============== BÚSQUEDA ALEATORIA ===============

,T,RMSE,RMSE_std,MAE,MAE_std,MAPE,MAPE_std,R2,R2_std,Importancia_Params,Parámetros
0,5,0.064333,0.018892,0.064333,0.015916,0.532777,0.421396,0.616143,0.092639,"{'learning_rate': np.float64(0.3368), 'batch_s...","{'lstm_units': 36, 'dense_units': 16, 'dropout..."
1,10,0.058966,0.023314,0.058966,0.018701,0.515943,0.464439,0.667923,0.126122,"{'batch_size': np.float64(0.3577), 'dropout': ...","{'lstm_units': 60, 'dense_units': 8, 'dropout'..."
2,15,0.053723,0.006241,0.053723,0.006670,0.392198,0.258683,0.693698,0.041781,"{'lstm_units': np.float64(0.4903), 'batch_size...","{'lstm_units': 52, 'dense_units': 28, 'dropout..."
3,20,0.046037,0.011061,0.046037,0.010751,0.385585,0.314621,0.774427,0.056534,"{'batch_size': np.float64(0.3434), 'learning_r...","{'lstm_units': 36, 'dense_units': 60, 'dropout..."

     T  Fold      RMSE       MAE      MAPE        R2
0    5     0  0.107230  0.086532  1.128681  0.511810
1    5     1  0.081639  0.056458  0.228876  0.599687
2    5     2  0.061043  0.050010  0.240773  0.736931
3   10     0  0.107407  0.084593  1.172754  0.510205
4   10     1  0.073585  0.051810  0.185399  0.674646
5   10     2  0.050645  0.040494  0.189676  0.818919
6   15     0  0.081930  0.062759  0.755536  0.715004
7   15     1  0.066929  0.046858  0.173586  0.730774
8   15     2  0.071879  0.051553  0.247471  0.635317
9   20     0  0.076630  0.059466  0.827881  0.750658
10  20     1  0.049537  0.033148  0.122483  0.852421
11  20     2  0.062977  0.045499  0.206392  0.720204

================= ALGORITMO TPE ==================

,T,RMSE,RMSE_std,MAE,MAE_std,MAPE,MAPE_std,R2,R2_std,Importancia_Params,Parámetros
0,5,0.055479,0.013788,0.055479,0.011780,0.654852,0.589067,0.706724,0.080177,"{'learning_rate': np.float64(0.5665), 'dropout...","{'lstm_units': 44, 'dense_units': 8, 'dropout'..."
1,10,0.051904,0.014243,0.051904,0.011880,0.626450,0.589640,0.740497,0.078576,"{'learning_rate': np.float64(0.4542), 'batch_s...","{'lstm_units': 44, 'dense_units': 12, 'dropout..."
2,15,0.044980,0.003862,0.044980,0.005520,0.525722,0.449752,0.803066,0.008436,"{'learning_rate': np.float64(0.5741), 'batch_s...","{'lstm_units': 36, 'dense_units': 60, 'dropout..."
3,20,0.038455,0.005596,0.038455,0.005699,0.496635,0.446327,0.840226,0.033431,"{'dropout': np.float64(0.3355), 'lstm_units': ...","{'lstm_units': 52, 'dense_units': 56, 'dropout..."

     T  Fold      RMSE       MAE      MAPE        R2
0    5     0  0.083266  0.068302  1.486504  0.619354
1    5     1  0.074720  0.058277  0.281039  0.687818
2    5     2  0.050697  0.039858  0.197013  0.812999
3   10     0  0.077188  0.064470  1.459952  0.672895
4   10     1  0.073501  0.055280  0.231387  0.697919
5   10     2  0.045299  0.035962  0.188013  0.850676
6   15     0  0.061429  0.050289  1.161709  0.792829
7   15     1  0.057754  0.047284  0.215171  0.813489
8   15     2  0.052042  0.037368  0.200286  0.802879
9   20     0  0.058404  0.046353  1.127827  0.812698
10  20     1  0.044893  0.033110  0.177976  0.887279
11  20     2  0.049641  0.035903  0.184102  0.820702

## Parámetros e importancia de los mismos

In [3]:
# Lista de valores de T 
valores_T = [5, 10, 15, 20]


# BÚSQUEDA ALEATORIA
print(f"{' RESULTADOS: BÚSQUEDA ALEATORIA ':=^60}\n")

for i in range(4):
    print(f"[T = {valores_T[i]}]")
    print(f"Importancia parámetros: {df_principal_random['Importancia_Params'][i]}")
    print(f"Configuración: {df_principal_random['Parámetros'][i]}\n")


# ALGORITMO TPE
print(f"\n{' RESULTADOS: ALGORITMO TPE ':=^60}\n")

for i in range(4):
    print(f"[T = {valores_T[i]}]")
    print(f"Importancia parámetros: {df_principal_TPE['Importancia_Params'][i]}")
    print(f"Configuración: {df_principal_TPE['Parámetros'][i]}\n")

============== RESULTADOS: BÚSQUEDA ALEATORIA ==============

[T = 5]
Importancia parámetros: {'learning_rate': np.float64(0.3368), 'batch_size': np.float64(0.1883), 'dropout': np.float64(0.1857), 'lstm_units': np.float64(0.1526), 'dense_units': np.float64(0.1366)}
Configuración: {'lstm_units': 36, 'dense_units': 16, 'dropout': 0.3381039081951648, 'learning_rate': 0.0005799505622011225, 'batch_size': 64}

[T = 10]
Importancia parámetros: {'batch_size': np.float64(0.3577), 'dropout': np.float64(0.2242), 'learning_rate': np.float64(0.2182), 'dense_units': np.float64(0.1711), 'lstm_units': np.float64(0.0289)}
Configuración: {'lstm_units': 60, 'dense_units': 8, 'dropout': 0.46992188575646593, 'learning_rate': 0.0014054250873712457, 'batch_size': 128}

[T = 15]
Importancia parámetros: {'lstm_units': np.float64(0.4903), 'batch_size': np.float64(0.1965), 'dropout': np.float64(0.1404), 'learning_rate': np.float64(0.1258), 'dense_units': np.float64(0.0469)}
Configuración: {'lstm_units': 52, 'dense_units': 28, 'dropout': 0.4313254230372521, 'learning_rate': 0.001039279801134998, 'batch_size': 64}

[T = 20]
Importancia parámetros: {'batch_size': np.float64(0.3434), 'learning_rate': np.float64(0.273), 'dense_units': np.float64(0.1815), 'lstm_units': np.float64(0.1144), 'dropout': np.float64(0.0877)}
Configuración: {'lstm_units': 36, 'dense_units': 60, 'dropout': 0.3503452609497175, 'learning_rate': 0.0009724693029321929, 'batch_size': 128}


================ RESULTADOS: ALGORITMO TPE =================

[T = 5]
Importancia parámetros: {'learning_rate': np.float64(0.5665), 'dropout': np.float64(0.2893), 'dense_units': np.float64(0.0548), 'lstm_units': np.float64(0.0475), 'batch_size': np.float64(0.0419)}
Configuración: {'lstm_units': 44, 'dense_units': 8, 'dropout': 0.17014248815180033, 'learning_rate': 0.004270483211236656, 'batch_size': 256}

[T = 10]
Importancia parámetros: {'learning_rate': np.float64(0.4542), 'batch_size': np.float64(0.2133), 'lstm_units': np.float64(0.1862), 'dropout': np.float64(0.1055), 'dense_units': np.float64(0.0409)}
Configuración: {'lstm_units': 44, 'dense_units': 12, 'dropout': 0.22865498924004302, 'learning_rate': 0.003653234272191966, 'batch_size': 512}

[T = 15]
Importancia parámetros: {'learning_rate': np.float64(0.5741), 'batch_size': np.float64(0.1326), 'lstm_units': np.float64(0.1287), 'dropout': np.float64(0.1075), 'dense_units': np.float64(0.0571)}
Configuración: {'lstm_units': 36, 'dense_units': 60, 'dropout': 0.36931587006616945, 'learning_rate': 0.0033593958022635206, 'batch_size': 256}

[T = 20]
Importancia parámetros: {'dropout': np.float64(0.3355), 'lstm_units': np.float64(0.3346), 'batch_size': np.float64(0.1461), 'learning_rate': np.float64(0.1246), 'dense_units': np.float64(0.0591)}
Configuración: {'lstm_units': 52, 'dense_units': 56, 'dropout': 0.31559843288470757, 'learning_rate': 0.0012146552050623515, 'batch_size': 128}